accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path(r'login/', views.LoginView.as_view(), name='login'),
    path(r'register/', views.RegisterView.as_view(), name='register'),
    path(r'logout/', views.LogoutView.as_view(), name='logout'),
    path(r'profile/', views.ProfileView.as_view(), name='profile'),
    path(r'profile/<path:field>/', views.ProfileUpdateView.as_view())
]

index/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'index'
urlpatterns = [
    path(r'', views.IndexView.as_view()),
    path(r'search/', views.SearchView.as_view())
]


surprise_music/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(r'', include('index.urls', namespace='index')),
    path('admin/', admin.site.urls),
    path(r'accounts/', include('accounts.urls', namespace='accounts')),
    path(r'music/', include('music.urls', namespace='player'))
]

templates/basic/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap -->
        <link href="{% static 'css/bootstrap.css'%}" rel="stylesheet">
        <!--你自己的样式文件 -->
        <link href="{% static 'css/reset.css' %}" rel="stylesheet">
        <script src="{% static 'sweetalert-master/docs/assets/sweetalert/sweetalert.min.js' %}"></script>

        <!-- 以下两个插件用于在IE8以及以下版本浏览器支持HTML5元素和媒体查询，如果不需要用可以移除 -->
        <!--[if lt IE 9]>
        <!--<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>-->
        <!--<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>-->
        {% block head %}
            <title>Bootstrap的HTML标准模板</title>
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-inverse">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">Surprise</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/">推荐<span class="sr-only">(current)</span></a></li>
                <li><a href="/music/">我的音乐</a></li>
                </li>
              </ul>
              <form class="navbar-form navbar-left" action="/search/" method="get">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search" name="music">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
              </form>
              <ul class="nav navbar-nav navbar-right">
                {% if user.id %}
                    <li><a href="{% url 'accounts:login' %}">{{ user.username }}</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}">登录</a></li>
                {% endif %}
                <li class="dropdown">
                    {% if user.id %}
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img class="img-rounded img-responsive min-mugshot" src="/static{{ user.mugshot }}"><span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="/accounts/profile/">账号设置</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/accounts/logout/">退出登录</a></li>
                      </ul>
                    {% else %}
                      <li><a href="{% url 'accounts:register' %}">注册</a></li>
                    {% endif %}
                </li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
        {% block main %}
            <div class="jumbotron">
              <h1>Hello, world!</h1>
              <p>...</p>
              <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
            </div>
        {% endblock %}
        <!-- 如果要使用Bootstrap的js插件，必须先调入jQuery -->
        <script src="https://www.imooc.com/static/lib/jquery/1.9.1/jquery.js"></script>
        <!-- 包括所有bootstrap的js插件或者可以根据需要使用的js插件调用　-->
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        {% block bottom %}
        {% endblock %}
    </body>
</html>